version: "3.7"

x-common:
  &default-common
  restart: always
  env_file: ./cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &default-common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  etcd:
    << : *default-common
    image: quay.io/coreos/etcd:v${LNMP_ETCD_VERSION:-3.4.1}
    networks:
      - frontend
      - backend
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - type: volume
        source: etcd-data
        target: /etcd-data
    command: [
      "/usr/local/bin/etcd",
      "--name s1",
      "--data-dir /etcd-data",
      "--listen-client-urls http://0.0.0.0:2379",
      "--advertise-client-urls http://0.0.0.0:2379",
      "--listen-peer-urls http://0.0.0.0:2380",
      "--initial-advertise-peer-urls http://0.0.0.0:2380",
      "--initial-cluster s1=http://0.0.0.0:2380",
      "--initial-cluster-token token",
      "--initial-cluster-state new"
      ]

volumes:
  etcd-data:
    << : *default-common-label
