version: "3.7"

x-common:
  &default-common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  example:
    << : *default-common
    image: example:${LNMP_ETCD_VERSION:-3.4.1}-alpine
