version: "3.7"

x-common:
  &default-common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  etcd:
    << : *default-common
    image: quay.io/coreos/etcd:v${LNMP_ETCD_VERSION:-3.4.1}
